### ISSUE TITLE
curl - bad url

### ISSUE THREAD

**Issue by volker-raschek** [ViViDboarder/drone-webdav#13]
Hello, I get the following [curl error][1] when drone runs into the upload step. Here my drone step:

```yaml
- name: push-latest-nextcloud
  image: vividboarder/drone-webdav
  file: index.pdf
  destination: https://nextcloud.cryptic.systems/remote.php/dav/files/fh-trier/Dokumente/Fachschaftdaten
  secrets:
  - webdav_username
  - webdav_password
  when:
    repo:
    - fh-trier/latex-templates
    event:
    - push
    - cron
```
Does anyone have an idea what should be wrong with the URL or is there a bug in the plugin?

[1]: https://drone.cryptic.systems/fh-trier/latex-templates/3/1/3

**Comment by ho-ho-ho** [comment]
Yeah I had problems with that too ... the plugin description is wrong. You should use:
```
- name: push-latest-nextcloud
  image: vividboarder/drone-webdav
  settings:
    file: index.pdf
    destination: https://nextcloud.cryptic.systems/remote.php/dav/files/fh-trier/Dokumente/Fachschaftdaten
  secrets:
  - webdav_username
  - webdav_password
  when:
    repo:
    - fh-trier/latex-templates
    event:
    - push
    - cron
```

The [Drone Plugin docs](https://docs.drone.io/plugins/overview/) also explain how you have to wrap the plugin settings in a settings section.
