### ISSUE TITLE
Multiple files: cUrl error bad/illegal format or missing URL

### ISSUE THREAD

**Issue by Rinma** [ViViDboarder/drone-webdav#14]
I tried different approaches (here shown as multiple file entries, that is not how I tried in on ci server):
```
- name: webdav_upload
  image: vividboarder/drone-webdav
  volumes:
  - name: cache
    path: /builds
  settings:
-----
    1. file: /builds/{moonshot_agenda_linux.zip,moonshot_agenda_windows.zip}
    2. file: /builds/moonshot_agenda_{linux,windows}.zip
    3. file: {/builds/moonshot_agenda_linux.zip,/builds/moonshot_agenda_windows.zip}
-----
    destination: https://cloud.example.org/remote.php/dav/files/username/folder/
    username:
      from_secret: webdav_username
    password:
      from_secret: webdav_password
  depends_on:
    - build_linux
    - build_windows
```

On the first two file entries I get this error:
```
latest: Pulling from vividboarder/******-webdav
Digest: sha256:0317da0cac39187ea8d48ddfae4328c0c330a8ebc597934c876359d39200f320
Status: Image is up to date for vividboarder/******-webdav:latest
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 11 54.6M    0     0   11 6688k      0  6461k  0:00:08  0:00:01  0:00:07 6455k
 84 54.6M    0     0   84 46.3M      0  22.7M  0:00:02  0:00:02 --:--:-- 22.7M
100 54.6M    0     0  100 54.6M      0  19.8M  0:00:02  0:00:02 --:--:-- 19.8M
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
````
The log shows that one of two files got uploaded, which I can confirm, but the second file then throws the error.

On the last file setting I get this error:
```
latest: Pulling from vividboarder/******-webdav
Digest: sha256:0317da0cac39187ea8d48ddfae4328c0c330a8ebc597934c876359d39200f320
Status: Image is up to date for vividboarder/******-webdav:latest
curl: Can't open '"/builds/moonshot_agenda_linux.zip":null'!
curl: try 'curl --help' or 'curl --manual' for more information
curl: (26) Failed to open/read local data from file/application
[ERROR] All upload attempts have failed.
```
Here it doesn't even find the file.

**Comment by nephatrine** [comment]
I'm seeing the same thing unfortunately. I think the comma is screwing up the parsing by drone.

For anyone else searching for this issue, you can just do this manually like this:

```yaml
- name: publish-web
  image: alpine/curl
  environment:
    WEBDAV_USERNAME:
      from_secret: webdav_username
    WEBDAV_PASSWORD:
      from_secret: webdav_password
  commands:
  - curl -T '/builds/moonshot_agenda_{linux,windows}.zip' --user "$WEBDAV_USERNAME:$WEBDAV_PASSWORD" 'https://cloud.example.org/remote.php/dav/files/username/folder/'
```
